export const CONTINUE_TO_THE_CAR = 'Continuar al carro'
export const FINISH_BUYING = 'Finalizar compra'
export const THANKS = '¡Gracias por confiar en nosotros!'
export const CONGRATULATIONS = 'Felicitaciones y Gracias por su compra!'
export const EXIT = 'Salir'
